blog_app/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    #working category
    path('',views.index,name='index'),
    path('dashboard',views.dashboard,name='dashboard'),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('register',views.register,name='register'),
    path('add',views.add,name='add'),
    path('search',views.search,name='search'),
    path('global',views.globalpage,name='globalpage'),
    path('comments/',views.commentsall,name='commentsall'),
    path('post/<str:title>',views.showpost,name='showpost'),
    path('user/<str:username>',views.showuser,name='showuser'),
    path('commentadding/<str:title>',views.commentadding,name='commentadding'),
    path('personalinfo',views.personalinfo,name='personalinfo'),
    path('comment/<str:title>/<int:id>',views.show_commentandreplies,name='showthiscomment'),
    path('addreply/<str:title>/<int:id>',views.addreply,name='addreply'),
    path('followuser/<str:username>/<str:usernameby>',views.followthis,name='followuser'),
    path('profileupdate',views.update_profile,name='updateprofile'),
    path('postupdate',views.update_post,name='postupdate'),
    #not working category
    path('about',views.about,name='about'),
    #waste category
    path('stats',views.stats,name='stats'),
    # otp checker and change password problem
    path('changepassword',views.change_pass,name='changepassword'),
    path('otpchecker',views.change_pass_otp,name='otpchecker'),
    
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#<div class="desc">{{ i.desc }}</div>
# features to be added

# channel not a feature
# telusko


# <div class="title">
#                 <label for="title">Title</label>
#                 <input type="text" name="title" id="title">
#             </div>
#             <div class="descs">
#                 <label for="description">Description</label>
#                 <textarea name="desc" id="desc" cols="30" rows="10"></textarea>
#             </div>
#             <div class="submitbutton">
#                 <button type="submit">Done</button>
#             </div>

text_bloging/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('blog_app.urls')),
    
]

blog_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django_quill.fields import QuillField
import datetime

# Create your models here.
class UserAccount(models.Model):
    user  = models.OneToOneField(User,on_delete=models.CASCADE)
    phone = models.CharField(max_length=12,null=True,default="")
    city = models.CharField(max_length=30,null=True,default="")
    state = models.CharField(max_length=30,null=True,default="")
    country = models.CharField(max_length=30,null=True,default="")
    address = models.CharField(max_length=400,null=True,default="")
    def __str__(self):
        return self.user.username

class Post(models.Model):
    # username = models.OneToOneField(User,on_delete=models.CASCADE)
    username = models.ForeignKey(UserAccount,on_delete=models.CASCADE)
    timeposted = models.TimeField(default=datetime.datetime.now,blank=True)
    title = models.CharField(primary_key=True,max_length=80,null=False,default="")
    blogbg = models.ImageField(upload_to='images',default=None)
    desc = QuillField(default='ici')
    def __str__(self):
        return self.username.user.username
# commentnew = Comment.object.create(postedwhere = Post.objects.filter(username = UserAccount.objects.filter(user=User.objects.filter(username='khushi')[0])[0]))
class Views(models.Model):
    postwhich = models.ForeignKey(Post,on_delete=models.CASCADE)
    views = models.IntegerField(default=1)
    def __str__(self):
        return self.postwhich.title

class Comment(models.Model):
    postedwhere = models.ForeignKey(Post,on_delete=models.CASCADE)
    userwhoposted = models.ForeignKey(UserAccount,on_delete=models.CASCADE)
    content = models.TextField()
    timeposted = models.TimeField()
    # commentedoncomment
    def __str__(self):
        return self.postedwhere.username.user.username


class Reply(models.Model):
    commentwhereposted = models.ForeignKey(Comment,on_delete=models.CASCADE)
    userwhoposted = models.ForeignKey(UserAccount,on_delete=models.CASCADE)
    content = models.TextField()
    timeposted = models.TimeField()
    # userwhomentioned = models.ForeignKey(UserAccount,on_delete=models.CASCADE)
    def __str__(self):
        return self.commentwhereposted.postedwhere.username.user.username

class OTPStorage(models.Model):
    username = models.ForeignKey(UserAccount,on_delete=models.CASCADE)
    otphere = models.CharField(max_length=6,null=False)
    timecreation = models.TimeField()
    timevalid = models.TimeField()
    def __str__(self):
        return self.username.user.username
    # def add_comment(objj:Comment):
    #     try:
    #         OTPStorage.comments.append(objj)
    #         return True
    #     except:
    #         return False

# class Followers(models.Model):
#     person = models.ForeignKey(UserAccount,on_delete=models.CASCADE)
#     followedby = models.ForeignKey(User,on_delete=models.CASCADE)
#     def __str__(self):
#         return self.person.user.username

class Following(models.Model):
    person = models.ForeignKey(UserAccount,on_delete=models.CASCADE)
    userfollowed = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.person.user.username
    
# class Meta:
#     unique_together = (('person','userfollowed'))
# class Meta:
#     constraints = [
#         models.UniqueConstraint(
#             fields=['person', 'userfollowed'], name='unique_migration_host_combination'
#         )
#     ]
    

templates/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        
        body{
            background-color: #EFFAD3;
            background-image: url('https://media.istockphoto.com/id/1395839130/photo/website-and-internet-contact-us-page-concept-with-phone-chat-email-mail-icons-symbol.jpg?s=612x612&w=0&k=20&c=NSgqVKI3VYf_tMsGBTQV4jJfqBswYiF0qW5okZIsGxA=');
            background-repeat: no-repeat;
            background-size: 100vw 100vh;
            display: flex;
            flex-direction: row;
        }
        .global{
            font-size: 25px;
            font-weight: 700;
            width: 35vw;
        }
        a{
            text-decoration: none;
            color: black;
        }
        .images-info{
            display: flex;
            flex-direction: column;
        }
        
        img{
            height: 130px;
            width: 130px;
        }
        .About{
            display: flex;
            flex-direction: row;
            margin-left: auto;
        }
        
    </style>
</head>
<body>
    <div class="global">
        
        <a href="{% url 'globalpage' %}">Global forum</a>
    </div>
    <div class="images-info">
        <div class="About">
            <p>Detail-oriented problem-solver, skilled in optimizing code. Strong communicator and leader, adaptable to new technologies. Dedicated and continuously learning, poised for impactful contributions in software engineering.</p>
            <img src="/media/aboutphotos/WhatsApp Image 2023-05-17 at 11.36.52.jpeg" alt="" srcset="" />
        </div>
        <div class="About">
            <p>Creative thinker, adept at designing intuitive user interfaces. Collaborative and adaptable to changing requirements. Motivated and quick learner, poised to excel in software engineering.</p>
            <img src="/media/aboutphotos/WhatsApp Image 2023-05-17 at 11.44.29.jpeg" alt="" srcset="" />
        </div>
        <div class="About">
            <p>Methodical and precise programmer, excelling in algorithm development. Strong problem-solving skills and quick to grasp new concepts. Detail-oriented and determined, destined for success in software engineering.</p>
            <img src="/media/aboutphotos/WhatsApp Image 2023-05-17 at 11.49.53.jpeg" alt="">
        </div>
        <div class="About">
            <p>Versatile and adaptable coder, skilled in multiple programming languages. Excellent team player and communicator. Eager learner and passionate about software engineering, ready to tackle complex projects.</p>
            <img src="/media/aboutphotos/WhatsApp Image 2023-05-17 at 14.58.28.jpeg" alt="">
        </div>
    </div>
</body>
</html>

templates/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'changepassword' %}" method="post">
        {% csrf_token %}
        <div>
            <label for="username">Enter username</label>
            <input type="text" name="username" id="username">
        </div>
        <h5>{{ message }}</h5>
        <div>
            <button type="submit">get otp</button>
        </div>
    </form>
</body>
</html>

templates/checkotp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h4>Enter otp username and new password to update</h4>
    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" id="username">
        <input type="password" name="newpassword" id="newpassword">
        <input type="password" name="newpasswordconfirm" id="newpasswordconfirm">
        <br>
        <label for="otp">otp</label>
        <input type="text" name="otp" id="otp">
        <h5>{{ message }}</h5>
        <button type="submit">submit</button>
    </form>
</body>
</html>

templates/commentsall.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>

        .container-navbar{
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: center;
            background-color: #EFFAD3;
            height: 15vh;
            padding-left: 15px;
            padding-right: 15px;
            color: #28ABB9;
            border-bottom: 1px solid #4CF14C;
        }
        input{
            border-radius: 15px;
            border: none;
            height: 45px;
            background: none;
            
            background-color: #acdadf;
        }
        .home{
          font-weight: 700;
          font-size: 25px;
        }
        .textsizehandle{
          font-size: 15px;
        }
        
        .block{
          display: flex;
          flex-direction: column;
          justify-content: space-around;
          align-items: center;
          color: white;
          height: auto;
          font-size: 30px;
          background-color: #28ABB9;
          border-bottom: 1px solid #4CF14C;
          width: 80vw;
          margin-left: auto;
          margin-right: auto;
        }
        .container-postodd{
          background-color: white;
          color: #28ABB9;
        }
        .container-posteven{
          background-color: #28ABB9;
        }
        
    </style>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body><div class="container-navbar">
    <div class="home">
      <a id="blog-home" class="navbar-brand" href="{% url 'index' %}">Bloggggggggg</a>
    </div>
    <div class="search textsizehandle">
      <form action="{% url 'search' %}" method="post">
        {% csrf_token %}
        <input id="inputsearch" type="text" name="search" placeholder="   Search">
        <button type="submit"></button>
      </form>
    </div>
    <div class="profile textsizehandle">
      <b><h1><a id="about" class="about-class" href="{% url 'personalinfo' %}">Profile</a></h1></b>
    </div>
    <div class="about textsizehandle">
      <b><h1><a id="about" class="about-class" href="{% url 'about' %}">About</a></h1></b>
    </div>
    <div class="adding textsizehandle">
      <b><h2><a href="{% url 'add' %}">Create</a></h2></b>
    </div>
    <div class="global textsizehandle">
        <b><h2><a href="{% url 'globalpage' %}">global forum</a></h2></b>
    </div>
    <div class="logout textsizehandle">
        <b><h2><a href="{% url 'logout' %}">logout</a></h2></b>
    </div>
</div>
      <br>
      <div class="block">
        {% for i in comments %}
          {% if forloop.counter|divisibleby:"2" %}
          <div class="container-posteven">
            <a href="{% url 'showthiscomment' title=i.postedwhere.title id=i.id %}">
            <div class="heading">{{ i.userwhoposted.user.username }} {{ i.timeposted }}</div>
            <div class="content">
                <!-- <div class="title">{{ i.title }}</div> -->
                <div class="desc">{{ i.content }}</div>
            </div>
            </a>
        </div>
          {% else %}
          <div class="container-postodd">
            <a href="{% url 'showthiscomment' title=i.postedwhere.title id=i.id %}">
            <div class="heading">{{ i.userwhoposted.user.username }} {{ i.timeposted }}</div>
            <div class="content">
                <!-- <div class="title">{{ i.title }}</div> -->
                <div class="desc">{{ i.content }}</div>
            </div>
            </a>
        </div>
          {% endif %}
        </a>
        {% endfor %}
    </div>
    
</body>
</html>
<!-- .block{
    max-width: 50%;
    border: 1px solid black;
    justify-content: center;
    display: flex;
    flex-direction: column;
    margin-left: 25%;
}
.container{
    display: flex;
    flex-direction: column;
    justify-content: center;
    border: 1px solid black;
}
.child-nav{
    display: none;
}
.parent-nav:hover .child-nav{
    display: block;
} -->

templates/globalpage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Global</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <style>
        .container-navbar{
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: center;
            background-color: #EFFAD3;
            height: 15vh;
            padding-left: 15px;
            padding-right: 15px;
            color: #28ABB9;
            border-bottom: 1px solid #4CF14C;
        }
        input{
            border-radius: 15px;
            border: none;
            height: 45px;
            background: none;
            background-color: #acdadf;
        }
        .home{
          font-weight: 700;
          font-size: 25px;
        }
        .textsizehandle{
          font-size: 15px;
        }
        .welcomeheader{
          display: flex;
          flex-direction: column;
          justify-content: space-around;
          align-items: center;
          color: white;
          height: 25vh;
          padding-left: 15px;
          padding-right: 15px;
          background-color: #28ABB9;
          border-bottom: 1px solid #4CF14C;
        }
        #welcoming{
          font-size: 24px;
        }
        
        .block{
          width: 100%;
          height: 100%;
        }
        .blockinsider{
          display: flex;
          justify-content: space-evenly;
          padding: 0px;
          width: 100%;
          flex-flow: row wrap;
          font-size: 30px;
        }
        .container-postodd{
          background-color: white;
          color: #28ABB9;
          width: 30vw;
          height: 35vh;
        }
        .container-posteven{
          background-color: #28ABB9;
          width: 30vw;
          height: 35vh;
        }
        .bgimage-posts{
          height: 35vh;
          width: 30vw;
        }
        .bgimage-posts>img{
          height: 100%;
          width: 100%;
        }
        .contain-it{
          margin-bottom: 15px;
        }
    </style>
</head>
<body>
    <div class="container-navbar">
        <div class="home">
          <a id="blog-home" class="navbar-brand" href="{% url 'index' %}">Bloggggggggg</a>
        </div>
        <div class="search textsizehandle">
          <form action="{% url 'search' %}" method="post">
            {% csrf_token %}
            <input id="inputsearch" type="text" name="search" placeholder="   Search">
            <button type="submit"></button>
          </form>
        </div>
        <div class="profile textsizehandle">
          <b><h1><a id="about" class="about-class" href="{% url 'personalinfo' %}">Profile</a></h1></b>
        </div>
        <div class="about textsizehandle">
          <b><h1><a id="about" class="about-class" href="{% url 'about' %}">About</a></h1></b>
        </div>
        <div class="adding textsizehandle">
          <b><h2><a href="{% url 'add' %}">Create</a></h2></b>
        </div>
        <div class="global textsizehandle">
            <b><h2><a href="{% url 'dashboard' %}">Dashboard</a></h2></b>
        </div>
        <div class="logout textsizehandle">
            <b><h2><a href="{% url 'logout' %}">logout</a></h2></b>
        </div>
    </div>
      <div class="block" style="display: flexbox; flex-direction:row; flex-wrap:wrap;">
        <div class="blockinsider" style="width: 100%; padding: 15px;">
        {% for i in allposted %}
        <a href="{% url 'showpost' title=i.title %}">
            {% if forloop.counter|divisibleby:"2" %}
            <div class="contain-it">
              <div class="bgimage-posts">
                {% if i.blogbg %}
                
                <img src="{{ i.blogbg.url }}" alt="user" />
                {% else %}
                <img src="https://img.freepik.com/free-photo/overhead-view-coffee-cup-keyboard-camera-paper-white-background_23-2148042112.jpg" alt="default" />  
                {% endif %}
              </div>
            <div class="container-posteven">
                <div class="heading">{{ i.username }} {{ i.timeposted }}</div>
                <div class="content">
                    <div class="title">{{ i.title }}</div>
                    
                </div>
            </div>
            </div>
          {% else %}
          <div class="contain-it">
            <div class="bgimage-posts">
              {% if i.blogbg %}
              
              <img src="{{ i.blogbg.url }}" alt="user" />
              {% else %}
              <img src="https://img.freepik.com/free-photo/overhead-view-coffee-cup-keyboard-camera-paper-white-background_23-2148042112.jpg" alt="default" />  
              {% endif %}
            </div>
            <div class="container-postodd">
                <div class="heading">{{ i.username }} {{ i.timeposted }}</div>
                <div class="content">
                    <div class="title">{{ i.title }}</div>
                </div>
            </div>
            </div>
          {% endif %}
            
        </a>
        {% endfor %}
        {% for i in comments %}
            <div class="container">
                <div class="heading">{{ i.timeposted }} {{ i.userwhoposted }}</div>
                <div class="content">
                    <div class="title">{{ i.content }}</div>
                    <!-- <div class="desc">{{ i.desc }}</div> -->
                </div>
            </div>
        {% endfor %}
    </div>
    <!-- </div> -->
    </div>
</body>
</html>
<!-- <div class="container">
    <div class="heading">{{ i.username }} {{ i.timeposted }}</div>
    <div class="content">
        <div class="title">{{ i.title }}</div>
        <div class="desc">{{ i.desc }}</div>
    </div>
</div> -->

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    <style>
        .container-navbar{
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: center;
            background-color: #EFFAD3;
            height: 15vh;
            padding-left: 15px;
            padding-right: 15px;
            color: #28ABB9;
            border-bottom: 1px solid #4CF14C;
        }
        input{
            border-radius: 15px;
            border: none;
            height: 45px;
            background: none;
            
            background-color: #acdadf;
        }
        .home{
          font-weight: 700;
          font-size: 25px;
        }
        .textsizehandle{
          font-size: 15px;
        }
        .welcomeheader{
          display: flex;
          flex-direction: column;
          justify-content: space-around;
          align-items: center;
          color: white;
          height: 25vh;
          padding-left: 15px;
          padding-right: 15px;
          background-color: #28ABB9;
          border-bottom: 1px solid #4CF14C;
        }
        #welcoming{
          font-size: 24px;
        }
        .block{
          width: 100%;
          height: 100%;
        }
        .blockinsider{
          display: flex;
          justify-content: space-evenly;
          padding: 0px;
          width: 100%;
          flex-flow: row wrap;
          font-size: 30px;
        }
        .container-postodd{
          background-color: white;
          color: #28ABB9;
          width: 30vw;
          height: 35vh;
        }
        .container-posteven{
          background-color: #28ABB9;
          width: 30vw;
          height: 35vh;
        }
        .bgimage-posts{
          height: 35vh;
          width: 30vw;
        }
        .bgimage-posts>img{
          height: 100%;
          width: 100%;
        }
        .contain-it{
          margin-bottom: 15px;
        }
    </style>
    <!-- <link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet"> -->
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <div class="container-navbar">
        <div class="home">
          <a id="blog-home" class="navbar-brand" href="{% url 'index' %}">Bloggggggggg</a>
        </div>
        <div class="search textsizehandle">
          <form action="{% url 'search' %}" method="post">
            {% csrf_token %}
            <input id="inputsearch" type="text" name="search" placeholder="   Search">
            <button type="submit"></button>
          </form>
        </div>
        <div class="profile textsizehandle">
          <b><h1><a id="about" class="about-class" href="{% url 'personalinfo' %}">Profile</a></h1></b>
        </div>
        <div class="about textsizehandle">
          <b><h1><a id="about" class="about-class" href="{% url 'about' %}">About</a></h1></b>
        </div>
        <div class="adding textsizehandle">
          <b><h2><a href="{% url 'add' %}">Create</a></h2></b>
        </div>
        <div class="global textsizehandle">
            <b><h2><a href="{% url 'globalpage' %}">global forum</a></h2></b>
        </div>
        <div class="logout textsizehandle">
            <b><h2><a href="{% url 'logout' %}">logout</a></h2></b>
        </div>
    </div>
    <div class="welcomeheader">
        <h1 id="welcoming">Welcome {{ request.user.username }}</h1>
        <h3>Share your knowledge and thoughts with us  😃</h3>
    </div>
    <div class="block" style="display: flexbox; flex-direction:row; flex-wrap:wrap;">
      <div class="blockinsider" style="width: 100%; padding: 15px;">
        {% for i in username %}
        <a href="{% url 'showpost' title=i.title %}">
          {% if forloop.counter|divisibleby:"2" %}
          <div class="contain-it">
            <div class="bgimage-posts">
              {% if i.blogbg %}
              
              <img src="{{ i.blogbg.url }}" alt="user" />
              {% else %}
              <img src="https://img.freepik.com/free-photo/overhead-view-coffee-cup-keyboard-camera-paper-white-background_23-2148042112.jpg" alt="default" />  
              {% endif %}
            </div>
            <div class="container-posteven">
                <div class="heading">{{ i.username }} {{ i.timeposted }}</div>
                <div class="content">
                    <div class="title">{{ i.title }}</div>
                    
                </div>
            </div>
          </div>
          {% else %}
          <div class="contain-it">
            <div class="bgimage-posts">
              {% if i.blogbg %}
                <img src="{{ i.blogbg.url }}" alt="user" />
              {% else %}
                <img src="https://img.freepik.com/free-photo/overhead-view-coffee-cup-keyboard-camera-paper-white-background_23-2148042112.jpg" alt="default" />
              {% endif %}
            </div>
            <div class="container-postodd">
                <div class="heading">{{ i.username }} {{ i.timeposted }}</div>
                <div class="content">
                    <div class="title">{{ i.title }}</div>
                </div>
            </div>
          </div>
          {% endif %}
        </a>
        {% endfor %}
      </div>
    </div>
</body>
</html>

templates/stats.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/updatepost.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update post</title>
    <style>
        .container-navbar{
            display: flex;
            flex-direction: row;
            justify-content: space-between;
            align-items: center;
            background-color: #EFFAD3;
            height: 15vh;
            padding-left: 15px;
            padding-right: 15px;
            color: #28ABB9;
            border-bottom: 1px solid #4CF14C;
        }
        input{
            border-radius: 15px;
            border: none;
            height: 45px;
            background: none;
            background-color: #acdadf;
        }
        .home{
          font-weight: 700;
          font-size: 25px;
        }
        .textsizehandle{
          font-size: 15px;
        }
        li{
          display: none;
        }
        a{
          text-decoration: none;
          color: #28ABB9;
        }
        #id_title{
          background: none;
          border: 1px solid #28ABB9;
          width: 100%;
        }
        .add-post-form{
          display: flex;
          flex-direction: column;
          margin-left: auto;
          margin-right: auto;
          margin-top: 15px;
          margin-bottom: auto;
          height: max-content;
          width: 70vw;
        }
        #itit{
          margin-top: 15px;
          background: none;
          border: 1px solid #28ABB9;
          width: 100%;
          height: 45px;
          border-radius: 15px;
          font-size: 20px;
          font-weight: 700;
          color: #28ABB9;
        }
    </style>
</head>
<body>
    <div class="container-navbar">
        <div class="home">
          <a id="blog-home" class="navbar-brand" href="{% url 'index' %}">Bloggggggggg</a>
        </div>
        
        <div class="profile textsizehandle">
          <b><h1><a id="about" class="about-class" href="{% url 'personalinfo' %}">Profile</a></h1></b>
        </div>
        <div class="about textsizehandle">
          <b><h1><a id="about" class="about-class" href="{% url 'about' %}">About</a></h1></b>
        </div>
        <div class="adding textsizehandle">
          <b><h2><a href="{% url 'add' %}">Create</a></h2></b>
        </div>
        <div class="global textsizehandle">
            <b><h2><a href="{% url 'globalpage' %}">global forum</a></h2></b>
        </div>
        <div class="logout textsizehandle">
            <b><h2><a href="{% url 'logout' %}">logout</a></h2></b>
        </div>
    </div>
    <div class="add-post-form">
        <form action="{% url 'postupdate' %}" method="post">
            {% csrf_token %}
            <div class="form-1">
            {{ form.media }}
            </div>
            <div class="form-2">
            {{ form.as_div }}
            </div>
            <input id="itit" type="submit" value="Add">
        </form>
    </div>
</body>
</html>